Repository watchdogpolska/feder, pull requests merged in 2020-11, with the labels that each got.

#884 Fix package-lock.json consistency
  package-lock.json
Labels: deps-frontend

#886 Script for importing institution CSV file previously exported by appl…
  api_examples/insert_institution_csv.py
  config/settings/common.py
  feder/institutions/views.py
  feder/institutions/viewsets.py
  feder/main/paginator.py
Labels: backend

#894 Show pending changes for frontend
  .github/workflows/frontend.yml
Labels: ci

#898 jst not required in the input file.
  api_examples/insert_institution_csv.py
  requirements/base.txt
  requirements/dev.txt
Labels: backend, deps-backend

#901 Tag ordering 870
  feder/institutions/views.py
Labels: backend

#912 Some improvements to institution import script.
  api_examples/insert_institution_csv.py
Labels: backend
