Repository watchdogpolska/feder, pull requests merged in 2020-10, with the labels that each got.

#859 Hotfix to broken bootstrap-sass collapse.
  feder/static/js/script.js
  feder/static/js/script.min.js
  package-lock.json
  package.json
Labels: deps-frontend, frontend

#868 Changed tag selection widget to checkboxes in institution edit page.
  docker-compose.yml
  feder/assets/scss/style.scss
  feder/institutions/forms.py
  feder/static/css/style.css
  feder/static/css/style.min.css
Labels: ci

#863 Institution import
  api_examples/insert_institution_generic.py
  api_examples/utils.py
  feder/institutions/admin.py
Labels: backend

#861 Readme and setup updates
  Makefile
  README.rst
  docs/development/development.rst
  feder/main/management/commands/create_social_app.py
  feder/main/management/commands/createsuperuserwithpassword.py
Labels: ci, docs

#873 Extend bootstrap time for Apache Tika
  Makefile
Labels: ci

#878 Sorting by name for tags with Ajax widget.
  feder/institutions/views.py
Labels: backend

#876 Used urlencode instead string concatenation.
  feder/institutions/views.py
Labels: backend

#879 Helper for CheckboxSelectMultiple widget which allows user to select/…
  docker-compose.yml
  feder/assets/js/widget.js
  feder/assets/scss/style.scss
  feder/monitorings/forms.py
  feder/static/css/style.css
  feder/static/css/style.min.css
  feder/static/js/script.js
  feder/static/js/script.min.js
  package-lock.json
  package.json
Labels: backend, ci, deps-frontend, frontend
