Repository watchdogpolska/feder, pull requests merged in 2021-07, with the labels that each got.

#1037 Added "Reply to {{EMAIL}}" to monitoring template and replies.
  feder/letters/forms.py
  feder/letters/utils.py
  feder/monitorings/forms.py
Labels: backend

#1041 Fixed error when trying to scan attachment of unrecognized letter.
  feder/letters/templates/letters/_btn.html
  feder/letters/templates/letters/attachment_base_object.html
Labels: frontend

#1043 Added additional filters to monitoring report.
  feder/cases/filters.py
  feder/cases/locale/pl/LC_MESSAGES/django.mo
  feder/cases/locale/pl/LC_MESSAGES/django.po
  feder/cases/models.py
  feder/cases/viewsets.py
  feder/monitorings/locale/pl/LC_MESSAGES/django.po
  feder/monitorings/templates/monitorings/_report_content.html
  feder/monitorings/views.py
Labels: backend, frontend

#1046 Drop djangorestframework-filters
  requirements/base.txt
Labels: deps-backend
