Repository watchdogpolska/feder, pull requests merged in 2022-10, with the labels that each got.

#1163 Deprecated node-sass replacement with sass
  .contrib/docker/Dockerfile.web
  .github/workflows/web.yml
  .pre-commit-config.yaml
  feder/static/css/style.css
  feder/static/css/style.min.css
  feder/static/js/script.js
  feder/static/js/script.min.js
  gulpfile.js
  package-lock.json
  package.json
Labels: frontend, deps-frontend, ci

#1161 Add hiding new cases
  .pre-commit-config.yaml
  feder/cases/locale/pl/LC_MESSAGES/django.mo
  feder/cases/locale/pl/LC_MESSAGES/django.po
  feder/monitorings/forms.py
  feder/monitorings/locale/pl/LC_MESSAGES/django.mo
  feder/monitorings/locale/pl/LC_MESSAGES/django.po
  feder/monitorings/migrations/0023_monitoring_hide_new_cases.py
  feder/monitorings/models.py
  feder/monitorings/tests.py
  feder/monitorings/views.py
Labels: backend

#1164 Replace deprecated ugettext for django 3+ compatibility
  Makefile
  config/settings/local.py
  feder/alerts/models.py
  feder/alerts/urls.py
  feder/alerts/views.py
  feder/cases/filters.py
  feder/cases/models.py
  feder/cases/serializers.py
  feder/cases/urls.py
  feder/cases/views.py
  feder/cases/viewsets.py
  feder/cases_tags/models.py
  feder/cases_tags/tests.py
  feder/cases_tags/urls.py
  feder/cases_tags/views.py
  feder/domains/apps.py
  feder/domains/models.py
  feder/institutions/admin.py
  feder/institutions/filters.py
  feder/institutions/models.py
  feder/institutions/urls.py
  feder/institutions/views.py
  feder/institutions/viewsets.py
  feder/letters/apps.py
  feder/letters/filters.py
  feder/letters/forms.py
  feder/letters/logs/apps.py
  feder/letters/logs/models.py
  feder/letters/logs/urls.py
  feder/letters/models.py
  feder/letters/tests/test_views.py
  feder/letters/types.py
  feder/letters/urls.py
  feder/letters/views.py
  feder/main/mixins.py
  feder/main/urls.py
  feder/monitorings/filters.py
  feder/monitorings/forms.py
  feder/monitorings/models.py
  feder/monitorings/serializers.py
  feder/monitorings/urls.py
  feder/monitorings/validators.py
  feder/monitorings/views.py
  feder/organisations/models.py
  feder/parcels/models.py
  feder/parcels/views.py
  feder/records/models.py
  feder/teryt/filters.py
  feder/teryt/urls.py
  feder/users/urls.py
  feder/virus_scan/models.py
  feder/virus_scan/urls.py
Labels: ci, backend
